<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function getDebtors()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('o')
            ->from('AppBundle\Entity\Order', 'o')
            ->where('o.debt > 0')
            ->getQuery()
            ->getResult();
    }

    public function getPreOrders()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('o')
            ->from('AppBundle\Entity\Order', 'o')
            ->where('o.isPreOrder = 1')
            ->getQuery()
            ->getResult();
    }
}
