<?php

namespace AppBundle\Entity\Repository;

/**
 * ProductGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
