<?php

namespace AppBundle\Entity\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveProducts()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('AppBundle\Entity\Product', 'p')
            ->andWhere('p.isDeleted = 0')
            ->orderBy('p.name', 'asc')
            ->getQuery()
            ->getResult();
    }
}
