<?php

namespace AppBundle\Entity\Repository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMonth($date)
    {
        return $this->findByMonthAndClient($date);
    }

    public function findByMonthAndClient($date, $client = null)
    {
        $startDate = (new \DateTime($date))->modify('first day of this month');
        $endDate = (new \DateTime($date))->modify('first day of next month');

        $result = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('s')
            ->from('AppBundle\Entity\Subscription', 's')
            ->where('s.date >= :start_date')
            ->andWhere('s.date < :end_date')
            ->andWhere('s.isDeleted = 0')
            ->setParameter('start_date', $startDate)
            ->setParameter('end_date', $endDate)
            ->orderBy('s.date', 'desc');

        if ($client != null)
        {
            $result
                ->andWhere('s.client = :client_id')
                ->setParameter('client_id', $client->getClientId());
        }

        $result = $result->getQuery()->getResult();

        return $result;
    }
}
