AppBundle\Entity\Attach:
    type: entity
    table: attach
    repositoryClass: AppBundle\Entity\Repository\AttachRepository
    indexes:
        fk_attach_client:
            columns:
                - client_id
    id:
        attachId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: attach_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: integer
            nullable: false
            options:
                default: 0
        location:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        link:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
            gedmo:
                timestampable:
                    on: create
    manyToOne:
        client:
            targetEntity: Client
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: attachs
            joinColumns:
                client_id:
                    referencedColumnName: client_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
