AppBundle\Entity\DiseaseHistory:
    type: entity
    table: disease_history
    repositoryClass: AppBundle\Entity\Repository\DiseaseHistoryRepository
    indexes:
        fk_desease_history_client:
            columns:
                - client_id
    id:
        diseaseHistoryId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: disease_history_id
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: false
            gedmo:
                timestampable:
                    on: create
        healthState:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: health_state
        treatment:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        client:
            targetEntity: Client
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: diseaseHistories
            joinColumns:
                client_id:
                    referencedColumnName: client_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
