AppBundle\Entity\MarketingReport:
    type: entity
    table: marketing_report
    repositoryClass: AppBundle\Entity\Repository\MarketingReportRepository
    indexes:
        fk_client_note:
            columns:
                - client_id
    id:
        marketingReportId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: marketing_report_id
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: false
        startSum:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0
            column: start_sum
        orderSum:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0
            column: order_sum
        contract:
            type: integer
            nullable: false
            options:
                default: 0
        contractSum:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0
            column: contract_sum
        maintenance:
            type: integer
            nullable: false
            options:
                default: 0
        maintenanceSum:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0
            column: maintenance_sum
    manyToOne:
        client:
            targetEntity: Client
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: notes
            joinColumns:
                client_id:
                    referencedColumnName: client_id
            orphanRemoval: false
    lifecycleCallbacks: {  }