AppBundle\Entity\OrderItem:
    type: entity
    table: order_item
    repositoryClass: AppBundle\Entity\Repository\OrderItemRepository
    indexes:
        fk_order_item_order:
            columns:
                - order_id
        fk_order_item_product:
            columns:
                - product_id
    id:
        orderItemId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: order_item_id
            generator:
                strategy: IDENTITY
    fields:
        count:
            type: integer
            nullable: false
            options:
                unsigned: true
        cost:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                default: 0.00
        state:
            type: boolean
            nullable: false
            options:
                default: '0'
    manyToOne:
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: product_id
            orphanRemoval: false
        order:
            targetEntity: Order
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: items
            joinColumns:
                order_id:
                    referencedColumnName: order_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
