AppBundle\Entity\Product:
    type: entity
    table: product
    repositoryClass: AppBundle\Entity\Repository\ProductRepository
    indexes:
        fk_product_product_group:
            columns:
                - product_group_id
    id:
        productId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: product_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        price:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        pieceName:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: piece_name
        isDeleted:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_deleted
    manyToOne:
        productGroup:
            targetEntity: ProductGroup
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: products
            joinColumns:
                product_group_id:
                    referencedColumnName: product_group_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
