security:
    encoders:
        AppBundle\Entity\User: md5

    providers:
        main:
            entity: { class: AppBundle:User, property: login }

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, role: ROLE_ADMIN }