<?php

namespace AppBundle\Entity\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    function getSortedClients()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from('AppBundle\Entity\Client', 'c')
            ->where('c.isDeleted = 0')
            ->orderBy('c.lastName, c.firstName, c.middleName','asc')
            ->getQuery()
            ->getResult();
    }

    function getFilteredByCheckboxes($isSubscribed, $isSchoolLearner, $isOnlineLearner)
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from('AppBundle\Entity\Client', 'c');

        if ($isSubscribed)
        {
            $qb->orWhere('c.isSubscribed = 1');
        }
        if ($isSchoolLearner)
        {
            $qb->orWhere('c.isSchoolLearner = 1');
        }
        if ($isOnlineLearner)
        {
            $qb->orWhere('c.isOnlineLearner = 1');
        }

        $qb->andWhere('c.isDeleted = 0');

        return $qb
            ->orderBy('c.lastName, c.firstName, c.middleName','asc')
            ->getQuery()
            ->getResult();
    }
}
